### PR TITLE
Add path for settings

### LINKED ISSUE #291: XML export on creation/update doesn't specify where the setting is
The "Cache description XML exports upon creation/modification" option described here: https://www.accesstomemory.org/en/docs/2.8/user-manual/import-export/export-xml/
Lacks a mention on where this setting is.
`An administrator does have the option of turning on a setting that will generate the XML for archival descriptions in advance on save`

And here: https://www.accesstomemory.org/en/docs/2.8/user-manual/administer/settings/#cache-xml-setting
Lacks a mention on where this setting is, or even what the setting is called.
`To avoid this, AtoM includes this setting, which allows users to pre-generate XML exports via AtoM's job scheduler, and then cache them in the downloads directory.`

Please add the path to get there in both paragraphs:
`Admin -> Settings -> Global Settings (scroll down to the bottom)`.

### PR DESCRIPTION
**Pull request by eviau-artefactual**
Closes https://github.com/artefactual/atom-docs/issues/291

Maybe this is not a good use case of the `rst_prolog` feature - https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_prolog ... let me know ?

### CODE REVIEW

**Comment by fiver-watson** [comment]
it may work, but reading about in the doc, it is not meant for random in-line subsitutions, but rather for adding static header (prolog) or footer (epilog) content that you want appended to _every_ page. At least that is how  I understand it: 

> **rst_prolog**
> * Type: str
> * Default: `' '`
>
> A string of reStructuredText that will be included at the beginning of every source file that is read. This is a possible place to add substitutions that should be available in every file 
> 

E.g. one possible use would be our CC license (though that is already in the website footer, so technically it is in fact visible on every page), or a docs version etc. 

If they change this feature to enhance its intended use this way in future versions of sphinx-docs, that could cause problems? Just a thought...

**Comment by eviau-artefactual** [comment]
I am trying to see if this is a good case to start [reusing content](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/reuse.html) to help with the [unique](https://www.writethedocs.org/guide/writing/docs-principles/#unique) feature of source...

Maybe it's too much for this path...?

**Comment by fiver-watson** [comment]
I think you actually answered your own question though with your links! The [RST substitution](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/reuse.html#use-a-substitution) is a general purpose solution for in-line changes like you were trying to implement. In fact we have used it before (I used it to swap in the header icons into the section titles on the Navigate page), I had just forgotten. 

On the other hand, the `rst_prolog` and `epilog` functions are specifically for page headers and footers that have repeated content. 

I would recommend using the substitution for what you've tried to do here instead, personally.

**Review by anvit — APPROVED** [review]
Looks good!

**Pull request merged**
