### PR TITLE
Update 'Requirements' help topic to include more specs for basic setup

### PR DESCRIPTION
**Pull request by currmie**
In a nutshell, added the following:
- More detailed specs for a basic setup on a single VM.
- Added minimal formatting/styling to align doc better with new AM-docs style guidelines per @sallain 

Note(s):
- @fiver-watson  originally described this task in Trello -- https://trello.com/c/oq6RO1kQ
- After reviews, editing, and merging PR, I'll apply to 2.5 docs.

### CODE REVIEW

**Review by fiver-watson — CHANGES_REQUESTED** [review]
Hi @currmie ! Thanks for this! 

One small change request: 

There is a long-standing convention in code writing to restrict the max width of a page's content to 80 characters. This dates back to the days in which this was the max width of a punch card, and the max display width of many early terminals. Those reasons no longer apply, as our tech has changed - but it also has to do with readability and the way the human eye/brain processes text. See for example:

* http://www.richarddingwall.name/2008/05/31/is-the-80-character-line-limit-still-relevant/
* https://stackoverflow.com/questions/4651012/why-is-the-default-terminal-width-80-characters

Can you please make sure to break your lines to match the width of the existing text?

One note on doing so: When you need to do this as part of an element like a bullet point, be sure that the subsequent line respects the indentation to the bullet (i.e. 3 spaces, to align it with the first line's text following the bullet). Otherwise, the element will through an error when you try to run the `make` command. The same is true within an admonition that spans multiple lines (such as the `: note::` element) - make sure everything is lined up under the note element after you insert line breaks. 

There are text editor packages that can help with this as well. For example, in Sublime Text, I have a package installed called AutoWrap that I've configured, so I can highlight any block of text, hit `ALT+Q` and it will hard wrap the text to my specified length. Atom and other editors should have equivalent packages available. I also recommend setting a ruler line in your text editor at 80 chars for reference, and setting tabs to use spaces (these things are usually configured in your settings). 

Also - I noticed you changed one of the existing ref anchors (`other-dependencies` changed to `other-dep`). Be careful doing so, as this could break links elsewhere in the documentation if anything links here. Be sure that you run `make clean html` when testing this locally (and not just `make html`) - this will flush any existing copies in `_build` and generate from scratch, so it will check all pages for warnings or errors (and should let you know if there's a link that's been broken by this change). I think this instance is probably fine (I can't think of another page that links right here), but be aware of this risk going forward, and please double-check this when you make changes. 

Otherwise, it looks great! Thank you!

**Comment by fiver-watson** [comment]
One more minor point! Can you change the commit message from "Updated" to "Update"? When you're ready, you should be able to do with with `git commit --amend`. 

Not a critical fix at all, but wanted to share best practice that I'm trying to stick to, re: commit messages, for consistency. I find this to be the best overview of best practices I've found: 

* https://chris.beams.io/posts/git-commit/

The recommendations are summarized as such: 

1. Separate subject from body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line
4. Do not end the subject line with a period
5. Use the present tense, imperative mood in the subject line
6. Wrap the body at 72 characters
7. Use the body to explain what and why vs. how

For small changes like this, it's fine to submit without a full description/body message if desired - but it's also very helpful to have a full commit message like this one! Thanks again!

**Comment by sallain** [comment]
@fiver-watson just an FYI that if you're in the _Files changed_ screen, you can leave suggestions directly on the text, at the line where the change is required.

**Comment by currmie** [comment]
@fiver-watson - Gah, I thought I set the max width in Sublime to 80 char! Will make requested changes and then merge! Thanks for the review.

**Pull request merged**
